--Creating info
INSERT INTO ACCOUNT VALUES (1,'clienteA');
INSERT INTO ACCOUNT VALUES (2,'clienteB');

INSERT INTO TARGET_DEVICE (ID_TARGET_DEVICE, ID_ACCOUNT, TARGET_DEVICE, PLUGIN_VERSION, PING_TIME) VALUES (1,1,'XBox','3.3.1',10);
INSERT INTO TARGET_DEVICE (ID_TARGET_DEVICE, ID_ACCOUNT, TARGET_DEVICE, PLUGIN_VERSION, PING_TIME) VALUES (2,1,'Panasonic','3.3.2',5);
INSERT INTO TARGET_DEVICE (ID_TARGET_DEVICE, ID_ACCOUNT, TARGET_DEVICE, PLUGIN_VERSION, PING_TIME) VALUES (3,2,'osmf','3.3.1',5);
