--Creating info
INSERT INTO ACCOUNT VALUES (1,'clienteA');
INSERT INTO ACCOUNT VALUES (2,'clienteB');

INSERT INTO PLUGIN VALUES (1,'3.3.1');
INSERT INTO PLUGIN VALUES (2,'3.3.2');

INSERT INTO TARGET_DEVICE (ID_TARGET_DEVICE, ID_ACCOUNT, TARGET_DEVICE, ID_PLUGIN_VERSION, PING_TIME) VALUES (1,1,'XBox',1,10);
INSERT INTO TARGET_DEVICE (ID_TARGET_DEVICE, ID_ACCOUNT, TARGET_DEVICE, ID_PLUGIN_VERSION, PING_TIME) VALUES (2,1,'Panasonic',2,5);
INSERT INTO TARGET_DEVICE (ID_TARGET_DEVICE, ID_ACCOUNT, TARGET_DEVICE, ID_PLUGIN_VERSION, PING_TIME) VALUES (3,2,'osmf',1,5);

INSERT INTO CLUSTER (ID_CLUSTER, CLUSTER_NAME) VALUES (1,'clusterA');
INSERT INTO CLUSTER (ID_CLUSTER, CLUSTER_NAME) VALUES (2,'clusterB');

INSERT INTO TARGET_DEVICE_X_CLUSTER (ID_CLUSTER, PERCENTAGE, ID_TARGET_DEVICE, ID_PLUGIN_VERSION) VALUES (1,70,1,1);
INSERT INTO TARGET_DEVICE_X_CLUSTER (ID_CLUSTER, PERCENTAGE, ID_TARGET_DEVICE, ID_PLUGIN_VERSION) VALUES (2,30,1,1);
INSERT INTO TARGET_DEVICE_X_CLUSTER (ID_CLUSTER, PERCENTAGE, ID_TARGET_DEVICE, ID_PLUGIN_VERSION) VALUES (2,100,2,2);
INSERT INTO TARGET_DEVICE_X_CLUSTER (ID_CLUSTER, PERCENTAGE, ID_TARGET_DEVICE, ID_PLUGIN_VERSION) VALUES (1,50,3,1);
INSERT INTO TARGET_DEVICE_X_CLUSTER (ID_CLUSTER, PERCENTAGE, ID_TARGET_DEVICE, ID_PLUGIN_VERSION) VALUES (2,50,3,1);